# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 07:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EVEAlliance',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('ticker', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EVECharacter',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('corp_id', models.CharField(max_length=254)),
                ('corp_name', models.CharField(max_length=254)),
                ('alliance_id', models.CharField(max_length=254, null=True)),
                ('alliance_name', models.CharField(max_length=254, null=True)),
                ('faction_id', models.CharField(max_length=254, null=True)),
                ('faction_name', models.CharField(max_length=254, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EVECorporation',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('alliance_id', models.CharField(max_length=254)),
                ('alliance_name', models.CharField(max_length=254)),
                ('members', models.CharField(max_length=254)),
                ('ticker', models.CharField(max_length=254)),
            ],
        ),
    ]
