# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecharacter',
            name='alliance_id',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='evecharacter',
            name='alliance_name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='evecharacter',
            name='faction_id',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='evecharacter',
            name='faction_name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
