# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVECorporation',
            fields=[
                ('corp_id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('corp_name', models.CharField(max_length=254)),
                ('alliance_id', models.CharField(max_length=254)),
                ('alliance_name', models.CharField(max_length=254)),
                ('members', models.CharField(max_length=254)),
                ('ticker', models.CharField(max_length=254)),
            ],
        ),
    ]
