# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0002_auto_20151207_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evecharacter',
            old_name='corporation_id',
            new_name='corp_id',
        ),
        migrations.RenameField(
            model_name='evecharacter',
            old_name='corporation_name',
            new_name='corp_name',
        ),
    ]
